# -*- coding: utf-8 -*-
"""syntax_surgion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ewp-gHxVOtu_Go_FgoIazXiCRvTOKpkf
"""

!pip install language-tool-python

import language_tool_python

# Initialize tool
tool = language_tool_python.LanguageTool('en-US')

def syntax_surgeon(text):
    matches = tool.check(text)
    corrected_text = language_tool_python.utils.correct(text, matches)
    return corrected_text

text = "She go to school everyday and play cricket"
print("Original Text:", text)

corrected = syntax_surgeon(text)
print("Corrected Text:", corrected)

user_text = input("Enter a sentence: ")
fixed_text = syntax_surgeon(user_text)

print("\nCorrected Sentence:")
print(fixed_text)